### ISSUE TITLE
REQUEST: Settings Options

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#1]
Love the module, seems to work great so far. My only recommendation would be to let users configure some options. Personally I love the hidden Foundry Logo, Shrunken Player List, and shrunk/repositioned lists. But I'd still like to keep the macro bar, the scene navigation, etc. If there was a way to turn each option on/off that'd be awesome.

And if you can accomplish that, it'd be great if you could make it so you can fully hide the player list entirely!

**Comment by saif-ellafi** [comment]
Thanks, I have restored the macro bar for now.
But certainly will work on making it configurable soon.

**Comment by saif-ellafi** [comment]
Feature request addressed as part of: a3f9d6c7ecad81be38f6ebc9286d12003bf139fc
