### ISSUE TITLE
The arrow to minimize scenes does not work

### ISSUE THREAD

**Issue by Avitale34** [saif-ellafi/foundryvtt-minimal-ui#10]
It seems like you can no longer maximize or minimize the scenes bar when you have this module active.
![image](https://user-images.githubusercontent.com/65961637/112390302-72aba280-8ccc-11eb-9a04-185c3319f00e.png)

**Comment by saif-ellafi** [comment]
Hello @Avitale34 thanks, can you help me reproduce this issue? Which other modules do you have enabled that could affect this?

It is likely another module interfering, otherwise I'd hope other people to have notice it too.

**Comment by Avitale34** [comment]
I tracked it down to the Bullseye module, it makes a right click option on the forge logo that I think is blocking the arrow.

**Comment by saif-ellafi** [comment]
Thanks, will take a look to see if I can do something about it!

**Comment by saif-ellafi** [comment]
Fixed in [0.3.4](https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/tag/0.3.4)
Please confirm :)

**Comment by Avitale34** [comment]
Works great! Thank you :)
