### ISSUE TITLE
PlayerList always hidden

### ISSUE THREAD

**Issue by CaosFR** [saif-ellafi/foundryvtt-minimal-ui#100]
Hi,

Thanks for this usefull module. A must have.
After install minimal ui and try differents options for the playerlist, My playerlist become always hidden, I can't see it. I have to use a script like that each time to activate it :

```
if (ui.players.rendered) 
{
ui.players.close();
}
else 
{
ui.players.render(true);
}
```

I dont have any error (F12). I use the last stable version of your module and foundry . I have try to disable or unintall your module, no result. Thanks for your help.

**Comment by saif-ellafi** [comment]
Hi @CaosFR - on which vesion of Foundry are you on?

**Comment by saif-ellafi** [comment]
I guess you have this, no?
![image](https://user-images.githubusercontent.com/27952699/190901332-342f4062-2110-4fa5-ad59-f65057a22f5c.png)

**Comment by CaosFR** [comment]
Hi,

This problem was solve when update to v10.
