### ISSUE TITLE
[REQUEST] Please add compatibility with "Taskbar" module

### ISSUE THREAD

**Issue by miusei** [saif-ellafi/foundryvtt-minimal-ui#101]
please add compatibility with Taskbar module from theripper93 ( https://theripper93.com/#/module/foundry-taskbar )

**Comment by saif-ellafi** [comment]
Hi @miusei - no way, that is a paid module. Sorry

**Comment by saif-ellafi** [comment]
You can use my other module, it also has a taskbar. https://foundryvtt.com/packages/window-controls

**Comment by miusei** [comment]
> You can use my other module, it also has a taskbar. https://foundryvtt.com/packages/window-controls

thank you <3

**Comment by saif-ellafi** [comment]
Welcome!!
