### ISSUE TITLE
Compatibility issue with Monk's Hotbar Expansion

### ISSUE THREAD

**Issue by davelamorte** [saif-ellafi/foundryvtt-minimal-ui#102]
Hello, this used to work, but since the latest update it doesn't anymore.
When the hotbar position is set to "extreme left", it now goes too much on the left, basically showing from the second button on.
![image](https://user-images.githubusercontent.com/46324776/189961798-8b6f9189-8a9d-4073-9052-c7c31f67f9cc.png)
If I choose "manual", I can place it wherever I want, also 1, but the players' list then doesn't go up, so it remains covered.

Ideally, if there's no easy way to fix this, having the possibility to choose the vertical position of the players' list would do the trick.
Thank you for your hard work! This module is one of the best!

**Comment by saif-ellafi** [comment]
Hey @davelamorte is this on Foundry v10? I just installed both and they work fine for me together
![image](https://user-images.githubusercontent.com/27952699/190901505-9c001022-279a-485b-9193-12f06d8c9f87.png)

**Comment by davelamorte** [comment]
No, I'm still on v9!
So I guess that's the issue?

**Comment by saif-ellafi** [comment]
Yes, sorry. Too much to maintain multiple versions and multiple modules. Let me know if you find issues on v10 onwards :)

**Comment by davelamorte** [comment]
I updated to V10, no issues so far.
Thank you for your hard work!
