### ISSUE TITLE
Request : Size of the A/V windows

### ISSUE THREAD

**Issue by CaosFR** [saif-ellafi/foundryvtt-minimal-ui#107]
Hi,

Thanks for your work and the update to v10. In v10 the camera of my players are so bigs !
Would it be possible to have an option to reduce the size of A/V windows and the dock ?

Thanks and happy dev

**Comment by jacksands** [comment]
In the meantime you use Custon CSS module and dont use TweakWRC you can use this css code:

/* v10 cameras sidebar resize drag */
div#camera-views {--av-width: auto;}

![image](https://user-images.githubusercontent.com/7229143/198830017-07651866-ed0e-4eef-a5ae-929b15efa946.png)


![image](https://user-images.githubusercontent.com/7229143/198829903-4112a828-4fad-44af-9792-779651f81bc5.png)

**Comment by CaosFR** [comment]
@jacksands Thanks for the tips ! I will use the dock with this CSS in the meantime.

**Comment by saif-ellafi** [comment]
ugh, this is ugly. I am super lazy to fix it... need to find the time, is the above style fixing everything?

**Comment by CaosFR** [comment]
@saif-ellafi Unfortely not, it's only fixe the size of the dock, but not the windows of the AV if we dont use the dock (my case).

**Comment by saif-ellafi** [comment]
Ah sorry I meant to comment in the other issue. This here is not a bug, just an enhancement to be able to make things smaller than minimum :)

**Comment by saif-ellafi** [comment]
done
