### ISSUE TITLE
Left/Right Dock AV window breaks with Players

### ISSUE THREAD

**Issue by jfrazierjr** [saif-ellafi/foundryvtt-minimal-ui#109]
Default(s) with no Mods running.

![image](https://user-images.githubusercontent.com/2130984/199539174-73366d4b-d542-4e80-8138-5bd83b4eb443.png)

![image](https://user-images.githubusercontent.com/2130984/199539303-40d41772-c484-40b6-a1cc-bcc07ad028a6.png)

Players menu is collapsible BELOW the AV div in core Foundry.

![image](https://user-images.githubusercontent.com/2130984/199539733-727ccda1-773f-4938-a03e-40e9ff3f3fdf.png)

Enabling JUST the minimal UI and it's dependency, the Players aside now completely covers the AV controls and makes them(the controls) completely unusable.

![image](https://user-images.githubusercontent.com/2130984/199540077-f8baa0ee-88ed-4368-81d8-aaed156c6648.png)

**Comment by saif-ellafi** [comment]
Hi @jfrazierjr can you please make sure you have Minimal UI version 1.5.4?

**Comment by jfrazierjr** [comment]
Thanks, that fixed the problem, or at least made the AV controls usable.

**Comment by saif-ellafi** [comment]
Awesome, have fun
