### ISSUE TITLE
Shadow Colors is incorrectly named Border Colors?

### ISSUE THREAD

**Issue by plutoneld** [saif-ellafi/foundryvtt-minimal-ui#11]
The settings mention Border Colors twice, I'm assuming the second option should be named Shadow Colors?

![image](https://user-images.githubusercontent.com/10401440/112433466-96a9cb00-8d42-11eb-9588-73a732f99b01.png)

**Comment by saif-ellafi** [comment]
oops, thank you!

**Comment by saif-ellafi** [comment]
Fixed in [0.3.4](https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/tag/0.3.4)
Thanks!!!
