### ISSUE TITLE
BUG: FPS Counter repositioned too far to the left with no option to reposition.

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#113]
Hi, for some reason with your module enabled the FPS Counter has about a 300 pixel buffer between it and the chat window, whereas by default it is positioned directly next to the chat window. I don't know if this is intentional or not, but if you're intentionally moving it, I'd request that you at least provide an option to move it back.

**Comment by saif-ellafi** [comment]
Fixed
