### ISSUE TITLE
Update for V11

### ISSUE THREAD

**Issue by EvldoaTV** [saif-ellafi/foundryvtt-minimal-ui#120]
ETA on Update for V11?
The Mod mo longer works, love the mod hope to see update soon

**Comment by strongpauly** [comment]
At a first glance, it appears to just be a case of declaring compatibility.  If you have it installed, and manually edit the module to say it can work on v11, then restart your server, it seems to work.

**Comment by EvldoaTV** [comment]
The mod can no longer be installed to V11 is what  I should have said

**Comment by saif-ellafi** [comment]
Hi @EvldoaTV @strongpauly - Released! Thank you
