### ISSUE TITLE
v11 bug

### ISSUE THREAD

**Issue by andy-jones** [saif-ellafi/foundryvtt-minimal-ui#123]
Works until anything appears in the chat panel, then as soon as a card is posted to the chat the whole chat panel shifts upwards so that the top menu is no longer visible. Tested this with all other add-ons switched off, and on multiple systems. Running latest version of Foundry.

**Comment by saif-ellafi** [comment]
Hi @andy-jones - could you please post a screenshot of what you mean?

**Comment by andy-jones** [comment]
Yes, of course.

See screenshot 1 attached - all looks fine and normal.

Screenshot 2 shows that once a card appears in the chat, the whole panel shifts upwards and you can’t see the menu at the top.

Hope that makes sense!

**Comment by saif-ellafi** [comment]
Hi @andy-jones - Thanks for the attempt, but I think screenshot attachments don't work from email in your case, or can't see them.
Any chance you post them here in GitHub?

**Comment by andy-jones** [comment]
![Screenshot1](https://github.com/saif-ellafi/foundryvtt-minimal-ui/assets/13047768/d17829f1-f79f-4a6d-a571-55f2ffbee780)

![Screenshot2](https://github.com/saif-ellafi/foundryvtt-minimal-ui/assets/13047768/d6b94da2-d292-4aed-8cc0-b97a3304acd1)

**Comment by andy-jones** [comment]
there we go!

**Comment by saif-ellafi** [comment]
Thanks - that's super weird. I don't do anything to the chat. Will have to check if this is something with this specific system. Is this CoC?

**Comment by saif-ellafi** [comment]
Ah alright, got it. I could reproduce it, will investigate asap and fix.
Thanks

**Comment by andy-jones** [comment]
Yes, that's CoC, but it also does it in other systems - I've tried it on MoSh (unofficial Mothership) and D&D5e too. Thanks for your hard work on this, it's a great module!

**Comment by saif-ellafi** [comment]
Hey @andy-jones fixed in 1.6.1 - Could you check?

**Comment by andy-jones** [comment]
Perfect! That seems to have fixed it! Thanks.

**Comment by saif-ellafi** [comment]
Sorry @andy-jones - I broke it again

**Comment by andy-jones** [comment]
ooops :D

**Comment by saif-ellafi** [comment]
@andy-jones fixed once again, I hope this time for good. Foundry v11 did some changes I needed to tweak more stuff to it.

**Comment by andy-jones** [comment]
All looks good to me. Thanks again.Sent from my iPhoneOn 23 Jun 2023, at 09:59, Saif Addin ***@***.***> wrote:﻿
@andy-jones fixed once again, I hope this time for good. Foundry v11 did some changes I needed to tweak more stuff to it.
