### ISSUE TITLE
No buttons/menus

### ISSUE THREAD

**Issue by eupatorus** [saif-ellafi/foundryvtt-minimal-ui#125]
This is what it appears like with just Minimal UI and lib-colorpicker (or wahtever the dependent is called) active.

![minimalui](https://github.com/saif-ellafi/foundryvtt-minimal-ui/assets/74635986/9bea35fa-7100-49fd-81b0-8dfa6b4932bd)

**Comment by saif-ellafi** [comment]
Thanks, confirmed, will fix

**Comment by saif-ellafi** [comment]
Hi @eupatorus - fixed, could you please confirm? :)
