### ISSUE TITLE
Suggestion: Only allow GM to see the Scene Navigation Preview

### ISSUE THREAD

**Issue by CasualTerror** [saif-ellafi/foundryvtt-minimal-ui#13]
For the Scene Navigation Preview setting. It might be best for that to be a GM-only feature or add an option for it to be GM only. I like for my players to have access to the world map at all times but if they switch scenes and then back having the scene preview pop out then they might see something in the preview of the dungeon that they haven't been to yet.

**Comment by saif-ellafi** [comment]
Hello @CasualTerror Thanks for the feedback, let me see if I understand the problem correctly:

The image preview is the thumbnail of the map, so they shouldn't be able to see anything through the "preview" if that's what you mean. It is a static image.

Are you sure you are not thinking the preview can show tokens or dynamic content from the scene, correct?

**Comment by SalieriC** [comment]
@saif-ellafi: I think what @CasualTerror means is, that the preview will show part of the dungeon or whatever they haven't yet discovered, thus allowing them to see where the final boss room or whatever is. I think this is a valid concern.

**Comment by saif-ellafi** [comment]
I see, the preview may reveal beyond the fog of war

**Comment by saif-ellafi** [comment]
Fixed in 0.4.3. Now this feature only works on GMs. Please confirm if all good when possible :)

**Comment by CasualTerror** [comment]
I installed the new version and it didn't change the mouseover preview on the top scene navigation.

This screenshot was taken from a player's POV. As you can see there's something interesting on the preview that I wish to keep hidden until they walk into that room.
![Screenshot 2021-03-26 192718](https://user-images.githubusercontent.com/32625656/112702312-7163ac80-8e69-11eb-903f-70076a156df7.jpg)

**Comment by saif-ellafi** [comment]
Gosh, I am really sorry. I didn't include the fix in the last release.

**Comment by saif-ellafi** [comment]
@CasualTerror 0.4.4 should have it effectively fixed :)
