### ISSUE TITLE
Player List in dock - visual bug

### ISSUE THREAD

**Issue by CaosFR** [saif-ellafi/foundryvtt-minimal-ui#132]
Hi,

Since update to v11 I have a problem with the player list when I use the dock in the left or right position.

See arrows in the screenshoot : 

![Capture d’écran 2023-08-31 231743](https://github.com/saif-ellafi/foundryvtt-minimal-ui/assets/37581932/d19cf9fe-3fab-44de-bc33-d8b7ab74617a)

System :
Foundry 11.308
DnD 5e 2.3.1
Tested with only minimal-ui 

Thanks for your help and your work

**Comment by Hufschmidt** [comment]
Same issue here, only happend when video/audio intergation if active and visible. 

Workaround: Detach sidebar into floating window.

**Comment by Hufschmidt** [comment]
The issue seems to stem from or be related to the 'Hide Player List' option of the video/audio side-panel, as clicking on it forces the same behaviour even when doing one of the workarounds. Hope this helps.

**Comment by CaosFR** [comment]
@saif-ellafi Any chance for update to fix this bug ?

**Comment by saif-ellafi** [comment]
Hi @Hufschmidt @CaosFR - Thanks for the patience, fixed and will release soon.

**Comment by saif-ellafi** [comment]
Released - please let me know how it goes :)

**Comment by CaosFR** [comment]
Solved for me thanks !
