### ISSUE TITLE
Hidden Foundry Logo

### ISSUE THREAD

**Issue by QuantumFunks** [saif-ellafi/foundryvtt-minimal-ui#14]
Could you add an option to toggle whether the logo is hidden? I want to use this module in conjuction with Display Mode which requires you to click on the logo to hide all elements. I want to use this module reduce the number of elements that appear when i click the logo, but its completely removed when this minimal ui is active.

Is it also possible to set different levels of UI reduction based on access permissions? (i.e. hide macro bar for players but not GM?)

**Comment by saif-ellafi** [comment]
He @QuantumFunks Thanks. Everything is configurable so there is no reason the logo is permanently hidden without an option.
I'll also take a look to the Display Mode module to make sure it all goes well.

Thanks

**Comment by QuantumFunks** [comment]
Thanks for the quick response. I wasnt able to find a hidden logo option in the module settings unless im overlooking something

**Comment by saif-ellafi** [comment]
Nono, you are right. There isn't. Will be adding the option soon :)

**Comment by QuantumFunks** [comment]
thanks a lot :)

**Comment by QuantumFunks** [comment]
not sure if its possible but if you could add afeature that collapses/hides all the elements by clicking the logo, thatd make the display mode essentially redundant haha

**Comment by SalieriC** [comment]
Maybe, while you're at it, you could push the nav bar to the left side of the screen if the logo is hidden. That'd preserve some precious screen real estate.

**Comment by saif-ellafi** [comment]
It's actually not a bad idea to hide everything as a toggle.  Hopefully that is not too bad against Display Mode author :)

@SalieriC I did that before and I removed as part of a major cleanup it on 0.4.x o_O I think shouldn't have done that. Will put it back.

**Comment by QuantumFunks** [comment]
Perhaps it could just be a multi option in the settings: click logo to hide all elements or click logo to collapse all elements. Then you arent being too bad :)

**Comment by saif-ellafi** [comment]
Done! Added two different sizes for the Foundry Logo (Small, Standard, Hidden) and also two toggable configurations (Click to hide all, click to hide all except Chat).
Hope you like it!

**Comment by QuantumFunks** [comment]
You're amazing, truly. This is such an amazing upgrade. 

Just a little heads up, i just tested both hide options and the chat window disappears in both. I made sure to fully restart the program to test it and it is persisting.

Another side note. When bullseye module is active, it no longer works.

**Comment by saif-ellafi** [comment]
Thanks Quantum for the kudos!

- Regarding the chat window disappearing in both, not happening to me :S. Tried both in my server and also on the local client. You sure you set "Hide ALL UI" option?
- Regarding bullseye. Yeah, sorry. That mode is poorly written in my opinion, it hardcode overrides the logo properties :( It is also not an authorized module in Foundry so it is less work for me to say that simply the support is minimal.

**Comment by QuantumFunks** [comment]
Yeah its strange. Ill have another few goes with both settings and see what happens.

Yeah i had a feeling that bullseye was going to be the issue here. Would it be possible to add a hotkey option to the hiding? that would literally fix everything. People could even assign it to a mouse or gaming keyboard button

**Comment by saif-ellafi** [comment]
Likely a conflicting module?

**Comment by QuantumFunks** [comment]
I still had display mode active, its working now. *facepalm*

Would you consider adding a hotkey option in a future release? Ill definitely preference your module over bullseye but itd be great to have a work around to use both

**Comment by saif-ellafi** [comment]
Thanks, I'll give it a thought over hotkey option. I am just "not sure" yet if the module should go in that direction. The settings panel is already growing long :D

Please open another separate feature request for hotkeys. Foundry Logo issue should be solved now.
