### ISSUE TITLE
Colour problem if right sidebar is collapsed

### ISSUE THREAD

**Issue by SalieriC** [saif-ellafi/foundryvtt-minimal-ui#15]
If the right side bar is collapsed, there is a tiny bar under the selected option that still shows the default colour:
![image](https://user-images.githubusercontent.com/1230041/115035640-11db4880-9ecd-11eb-8d11-e5570f9db750.png)

**Comment by saif-ellafi** [comment]
Gracias!!! Will fix it soon :)

**Comment by saif-ellafi** [comment]
Fixed!
