### ISSUE TITLE
Change "Close" with an X icon

### ISSUE THREAD

**Issue by apoapostolov** [saif-ellafi/foundryvtt-minimal-ui#17]
For further minimization of minimized tabs, change Close button with an X icon. Here's how a certain Pl...... mod does it. 

![image](https://user-images.githubusercontent.com/4083812/115219149-e5633e80-a10f-11eb-83ae-5b421d491d70.png)
![image](https://user-images.githubusercontent.com/4083812/115219180-ec8a4c80-a10f-11eb-940b-03010085d6cc.png)

You can of course forego the red coloring.

**Comment by saif-ellafi** [comment]
Thanks, that is true. I'll investigate how feasible this option is. But certainly it would save space!

**Comment by saif-ellafi** [comment]
Thanks for the idea! this is now achieved in 0.8.0, so about 50% space was saved! although not dynamically adjusted yet.
