### ISSUE TITLE
Anvil Icon - skinning instead of hiding it

### ISSUE THREAD

**Issue by apoapostolov** [saif-ellafi/foundryvtt-minimal-ui#18]
This is already covered by the mod MyTab, but you may find it fitting in your module focus.

Instead of removing the anvil icon in the upper right corner, allow the GM to skin it with the logo of their game system or stream.

**Comment by saif-ellafi** [comment]
This is a good idea! Thanks!

**Comment by saif-ellafi** [comment]
Provided as a new setting in 0.8.1 .. Enjoy !! :D
Feel free also to check my ko-fi page ^^
