### ISSUE TITLE
Dynamic width of minimized windows

### ISSUE THREAD

**Issue by apoapostolov** [saif-ellafi/foundryvtt-minimal-ui#19]
When Minimized, the width of the tabel could be dynamic based on the length of the text, instead fixed. This would make labels like the one below much shorter and fit more in your organized tabs.

![image](https://user-images.githubusercontent.com/4083812/115219461-3b37e680-a110-11eb-864b-a07338a02b5e.png)

**Comment by saif-ellafi** [comment]
This one is a bit tricky, because a fixed length allows me to easily manage the calculation of measuring available space. I will however investigate this further!

**Comment by saif-ellafi** [comment]
After some investigation. I am not very tempted on doing this. The gain is not really worth the work imho. With the cross as a button and the standard "small" width, we could be already happy with current functionality.

Will keep this issue open for a little longer until we experience a bit more how things are right now, before closing.

**Comment by saif-ellafi** [comment]
This is now part of Window Controls separate module
