### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by friction1** [saif-ellafi/foundryvtt-minimal-ui#2]
Hey, I like this module a lot and wanted to add a suggestion. It would be awesome to have scale bars (or a few size options) for fine tuning the size of the scenes at the top of the screen, icons on the left side of the screen, macro bar at the bottom of the screen. Thanks for considering!

**Comment by saif-ellafi** [comment]
Multiple sizes and options improved :) 
Please feel free to open new issues for new more specific requests.
Thanks
