### ISSUE TITLE
Resets settings every update

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#27]
Love the module! But every time you update it, most or all of my settings with it revert to their defaults, and I have to go back through and change it all back to how I had it before. Any chance you can get it to save the settings?

**Comment by saif-ellafi** [comment]
> Love the module! But every time you update it, most or all of my settings with it revert to their defaults, and I have to go back through and change it all back to how I had it before. Any chance you can get it to save the settings?

Thanks for reporting this. This should only have happened in the 0.8.0 update, not in all. I had unfortunately to go through deep changes and it was necessary to cause a few defaults on settings. But should not happen on any other update. If it happens in on any other update, please let me know.

**Comment by saif-ellafi** [comment]
Closing.
