### ISSUE TITLE
Show GM video frame only

### ISSUE THREAD

**Issue by MarceloCortezz** [saif-ellafi/foundryvtt-minimal-ui#3]
Hi, first of all: DAMN THIS MODULE IS AWESOME. Thanks!

I've been looking for a way to hide those video frames while showing only DM's but without success. I don't know how to code so I think your module could fit this functionality.

**Suggestion:** Hide all players' video frame while keeping GM's frame visible, so people could see GM faces while narrating the story without having a bunch of other frames open.

**Comment by saif-ellafi** [comment]
Thanks for the support, I will take a look at that. I think indeed it is weird that video is all or none, but not just the GM.

**Comment by saif-ellafi** [comment]
Hi @MarceloCortezz 
Added in 0.5.1 :) 80ef811593c75d15da53deefb43ffc29a64a2aa1
This is however border line for Minimal UI. I think Foundry VTT core should deal with this option.
Let me know your thoughts, have fun!
