### ISSUE TITLE
Make larger target to activate macro bar for macs

### ISSUE THREAD

**Issue by caewok** [saif-ellafi/foundryvtt-minimal-ui#30]
Foundry 0.7.9, minimal ui 0.8.8. 

On my mac, the application dock is at the bottom of the screen, and can be activated to appear by moving the cursor arrow nearly all the way to the bottom. Unfortunately, this conflicts with activating the macro hotbar in minimal ui. Basically, it is very fiddly, because if the mac dock activates, it takes focus away from the browser window and the hotbar will not activate. If you try really hard, you can get the hotbar to activate without activating the dock, but it is hard. 

Short-term solution is to lock the macro hotbar. Long-term, if the trigger area for activating the hotbar was larger in terms of space from the bottom, this could be avoided.

Thanks!

**Comment by saif-ellafi** [comment]
Thanks for reporting this!!! Unfortunately I don't have a Mac but we can brainstorm a little bit for solutions.
Increasing the detection area is one option but that would mean there's a lot more of shadow and border in the screen.
Let's think a bit more, but yes fixing the Macro Hotbar is one solution. Another is perhaps move the Hotbar along the X-Axis in case your apps Dock doesn't use all the space.

**Comment by caewok** [comment]
Some observations about how the macOS dock works:
- Default position is bottom of the screen, always visible. 
- It can be changed to appear only when you move the mouse to the edge of the screen with the dock ("hidden").
- Dock can be placed left, bottom, or right.
- Regardless of the length of the dock, when hidden, moving the mouse to anywhere along that screen edge makes it appear.
- When not hidden, it takes up the bottom portion of the screen. In most cases, this means the user cannot make an app window extend into the dock area. 
- When hidden, the user can extend an app window into the dock area. 
- The trigger for making a hidden dock appear is only a few pixels wide, along the very bottom of the screen.
- Once the hidden dock appears, it takes focus away from the window below.

I would guess that most macOS users that are interested in your module would have the dock hidden, to maximize real-estate and focus on the game. The dock will be a problem if it is either at the bottom or on the left side of the screen. But they can either keep it at the bottom and lock the macro hotbar, or temporarily move it to the left side. (Left, in my opinion, tends to be inferior b/c it interferes with window scroll bar usage.) So I would say this bug is lower priority, given those work-arounds.

If you have a way of increasing the detection area a bit without dramatically impacting the visuals, that would be a good approach. Basically, the user has to be able to stop just short of hitting the edge of the screen and have the relevant macro bar along the bottom or canvas controls along the left side to appear. So they need a slightly bigger target than what is there now, but not a lot.

**Comment by saif-ellafi** [comment]
This should be better now, as the autohide hotbar mode partially shows itself rather than its shadows, as earlier versions.
