### ISSUE TITLE
Scene Previews z-order happens behind the scene list

### ISSUE THREAD

**Issue by apoapostolov** [saif-ellafi/foundryvtt-minimal-ui#32]
Is this intended? Probably to allow to hover on the lower list but it looks a bit unattractive.

![image](https://user-images.githubusercontent.com/4083812/116305945-2103a580-a7ad-11eb-8fea-70d0225173fc.png)

**Comment by saif-ellafi** [comment]
Thanks, yes got to think about it. Scene Preview does not go well with many scenes that gather multiple rows. Foundry doesn't provide me a solid way of counting for the rows visible.

One possible solution is either to hide all scenes that are not being highlighted, but I'll continue investigating to find smarter solutions.

**Comment by saif-ellafi** [comment]
z-order is no solution because I don't want to block the other scenes with the preview either.

**Comment by saif-ellafi** [comment]
I have found a good solution for this, and will include it in the next release.

![image](https://user-images.githubusercontent.com/27952699/116386868-7f1aa200-a81a-11eb-86c0-3ffbf64cd95e.png)

**Comment by saif-ellafi** [comment]
Fixed in 0.9.0!!! Please confirm :)
