### ISSUE TITLE
Unable to open character sheets from the actor tab

### ISSUE THREAD

**Issue by agentnos** [saif-ellafi/foundryvtt-minimal-ui#34]
If you click on an actor in the actor tab to open their sheet, but then click the actor again, the sheet disappears and you are then unable to open it again, prompting this error:
![image](https://user-images.githubusercontent.com/6649313/116387223-8047d100-a812-11eb-88cb-e853108490c5.png)
Refreshing the page fixes this however.

**Comment by saif-ellafi** [comment]
Thank you @agentnos for coming to report this.

Could you make sure that you are on 0.8.8 version and this still happening? This was a bug introduced in 0.8.6 and fixed later.

**Comment by agentnos** [comment]
I just went through my modules to check they were all up to date, and this one wasn't. All up to date and it seems to all be working again! Thanks for the help!!!

**Comment by saif-ellafi** [comment]
Awesome!!! Enjoy :)
