### ISSUE TITLE
Organized Minimize mode treats "Bottom" option as "Top"

### ISSUE THREAD

**Issue by JLtheking2** [saif-ellafi/foundryvtt-minimal-ui#35]
Hello, as described, if the setting is set to Bottom and I minimize a character sheet, it gets sent to the top of the screen instead of the bottom. The bottom option used to work until I updated.

If I set the setting to "Bottom with Bar", it works as expected.

Tested with no mods loaded other than libWrapper, lib - Color Settings and Minimal UI.
Foundry 0.7.9
DnD5e 1.2.4

**Comment by saif-ellafi** [comment]
Thanks!! Will check out this asap this afternoon

**Comment by saif-ellafi** [comment]
Fixed in 0.9.1 ! Please confirm :)
