### ISSUE TITLE
[Suggestion] Remove the text in the new Minimize button

### ISSUE THREAD

**Issue by JLtheking2** [saif-ellafi/foundryvtt-minimal-ui#36]
Doing this would further compact the options bar just as you did with the close button in #17 . And I think everyone has used Windows enough to know what a straight line means 😄

**Comment by saif-ellafi** [comment]
I thought about it a lot! But concerned with the fact that it is not a "standard" in the rest of the buttons :( Would be an icon alone standing by itself. But Will consider about it.

**Comment by saif-ellafi** [comment]
Because the close button does also show the text when the window is expanded.

**Comment by saif-ellafi** [comment]
not a bad idea! could be optional, not sure if everyone likes it. Will write it down

**Comment by saif-ellafi** [comment]
Done in latest release! Enjoy and thanks for the feedback.
