### ISSUE TITLE
Dynamic Mode breaks when Polyglot module is enabled

### ISSUE THREAD

**Issue by Ghostdesu** [saif-ellafi/foundryvtt-minimal-ui#37]
**Describe the bug**
    Using dynamic mode alongside Polyglot module results in occasional "flicker" of the right side bar on scene change.

**To Reproduce**

    Enable Minimal UI, its dependencies and Polyglot.
    Enable Dynamic Mode in Minimal UI settings.
    Transition from one scene to another.

**Screenshots/GIFs/Videos**
    ![bugreport](https://user-images.githubusercontent.com/31375910/116601348-15da8200-a933-11eb-9490-342420bbb10f.gif)

**Desktop:**

    OS: Windows 10
    Browser: Firefox
    FVTT Version: 0.7.9
    DnD5e System Version: 1.2.4
    Minimal UI version: 0.9.0
    lib - Color Settings version: 2.5.9
    libWrapper version: 1.5.2.0
    Polyglot version: 1.5.15

    Tested with no other modules enabled.

**Additional context**
This behavior seems to be inconsistent affecting players more than GMs, further it seems to occur more often on larger maps which suggests it might have something to do with load time.

**Comment by saif-ellafi** [comment]
Thanks so much for reporting this. I am having a hard time watching that gif over and over again :D.
For the short term I'll unfortunately disable Dynamic Mode when Polyglot is active, and track down a solution over time.

**Comment by saif-ellafi** [comment]
hmm I am having difficulties reproducing it that obviously. I'll see what can it be.

**Comment by saif-ellafi** [comment]
ah yes I could now.

**Comment by saif-ellafi** [comment]
ok, it seems polyglot triggers chat rendering hundreds of times when switching scenes. I'll apply a fix on my end but it should be right to report that to the creator of that module.

**Comment by saif-ellafi** [comment]
Fixed for next release soon!

**Comment by saif-ellafi** [comment]
Fixed in 0.9.1 - Please confirm :)

**Comment by Ghostdesu** [comment]
Yep it's fixed now, thanks!
