### ISSUE TITLE
Request: support for new CoC control buttons

### ISSUE THREAD

**Issue by lozalojo** [saif-ellafi/foundryvtt-minimal-ui#38]
Not sure if it is possible to make Havlovk/CoC system (https://github.com/HavlockV/CoC7-FoundryVTT) buttons (the ones in green) homonegeus:

![](https://i.ibb.co/SPvYWQc/screenshot-175.jpg)

Thanks, great module!

**Comment by saif-ellafi** [comment]
Indeed, I am hoping to make minimal ui more compatible with other UIs as part of the next release.

**Comment by lozalojo** [comment]
> Indeed, I am hoping to make minimal ui more compatible with other UIs as part of the next release.

Great, thank you!

**Comment by saif-ellafi** [comment]
> > Indeed, I am hoping to make minimal ui more compatible with other UIs as part of the next release.
> 
> Great, thank you!

I have checked CoC. And unfortunately, it is the system's responsibility to apply the style to all buttons. Not to just the ones they add.

The best you can do from Minimal UI is to use the Standard Size buttons, and color the shadows and borders to something like this:
![image](https://user-images.githubusercontent.com/27952699/117055633-a6420980-ad1b-11eb-8708-566059a138d7.png)

**Comment by saif-ellafi** [comment]
0.9.6 with minor changes that should help overall with system styles. For the time being it is the best I could do.
