### ISSUE TITLE
Unofficial Card Support Issue

### ISSUE THREAD

**Issue by deraviin** [saif-ellafi/foundryvtt-minimal-ui#4]
Unofficial card support module is made to integrate into the macro hotbar, and does not collapse when minimal UI collapses it, leaving it floating in the middle of the screen.

It is unlikely any further changes will be made to UCS as it was considered complete and has not been touched in nearly half a year.

**Comment by saif-ellafi** [comment]
Thanks, I will see to make sure it works with UCS. Also other modules of interest such as Carousel Tracker and GM Screen.

**Comment by saif-ellafi** [comment]
Please follow them here: https://github.com/saif-ellafi/foundryvtt-minimal-ui/issues/6
