### ISSUE TITLE
Expanding the Right bar pops chat out.

### ISSUE THREAD

**Issue by Brimcon** [saif-ellafi/foundryvtt-minimal-ui#40]
Foundry Version 0.8.6
Not sure it matters but D&D5e 1.3.3
Minimal UI 1.0.1

Only Minimal UI and lib - color settings enabled
Clicking on the left arrow in the right bar pops chat out when it expands.

**Comment by saif-ellafi** [comment]
Thank you for reporting this, although I can't seem able to reproduce this error with latest versions of Minimal UI.

You seem to be using Minimal UI 1.0.1, which is a bit old. Could you try upgrading to a newer release please?

**Comment by Brimcon** [comment]
Updated Minimal UI and it seems the issue is fixed! Thanks!
