### ISSUE TITLE
[Suggestion] Hook for Foundry logo to hide other Modules' UI?

### ISSUE THREAD

**Issue by Juanfrank** [saif-ellafi/foundryvtt-minimal-ui#41]
Hello.-

Much of a noob in JS here. But is there any possibility of building a hook that would allow other modules to make their UI features toggle (hide/show) according to the Minimal UI's Foundry Logo setting? I believe that would be a really useful feature.

Thanks!

**Comment by saif-ellafi** [comment]
Thanks for suggesting this, although my first impression is that being able to do it selectively and universally is definitely tricky.

When in hide all mode, does the logo hide everything **including** other modules components already?

**Comment by Juanfrank** [comment]
Hello, sorry.

No it doesn't, I was suggesting building something like a "hook" that other modules authors can integrate into their code to hide/show their specific module UI.

**Comment by saif-ellafi** [comment]
Cannot do much here, need to support custom requested elements. Ideas welcome.
