### ISSUE TITLE
[ Question ] Left bar behind sheets and journal windows

### ISSUE THREAD

**Issue by MarceloCortezz** [saif-ellafi/foundryvtt-minimal-ui#42]
Is it possible to make the left menu stay behind of sheets and journal windows?
![image](https://user-images.githubusercontent.com/79060716/121551154-c71a1080-c9e5-11eb-948c-0efd015fae24.png)

**Comment by saif-ellafi** [comment]
I could not reproduce this on 0.8.9 anymore, could you recheck please?

![image](https://user-images.githubusercontent.com/27952699/129810132-d57d8540-4fe1-4403-8d42-df3fa25ed92e.png)

**Comment by saif-ellafi** [comment]
Closed for the moment.
