### ISSUE TITLE
Request: improve compatibility with Ping Logger module

### ISSUE THREAD

**Issue by Merudo** [saif-ellafi/foundryvtt-minimal-ui#43]
When combined with the Minimal UI module and the player list is set to auto-hide, the [Ping Logger](https://github.com/mawburn/foundry-ping-logger) module does not display the ping on the same line as the player colored dot:

![image](https://user-images.githubusercontent.com/7371085/128337504-65c4622d-4bb1-4745-9dcb-63609b059cf1.png)

As you see each player takes two lines in the player list, one for the colored dot and one for their ping.

Ideally, both should be displayed on the same line. Alternatively, the ping could be hidden when in auto-hide mode.

Also see https://github.com/mawburn/foundry-ping-logger/issues/1

**Comment by mawburn** [comment]
Nice job adding this to both repos.

I haven't looked into it yet, but my first thought is this looks like a flexbox display column. If that's the case, I should probably apply a class to the ping span that would make it get hidden along with the rest of the stuff. 

I haven't actually looked into this yet, but @saif-ellafi is there a class I can apply to it that will hide it?

**Comment by saif-ellafi** [comment]
I am a bit off the race for the moment but will track this down when I get some time. It will likely require some ruling from either side to make an exception. In the worst case scenario, setting up the Player List to look like vanilla should solve this.

If anyone has some time, a similar compatibilty patch was done with "Raise my Hand" module, i.e. by customizing some of the style parameters, plus some specific style changes to the class of the ping logger.
```
                    if (game.modules.has('raise-my-hand') && game.modules.get('raise-my-hand').active) {
                        rootStyle.setProperty('--playerwidth', '42px');
                        rootStyle.setProperty('--playerslh', '20px');
                    }
```

**Comment by Merudo** [comment]
Speaking of the compatibility patch, I get a lot of empty space on the right when the player is not hidden and set to standard size:

![image](https://user-images.githubusercontent.com/7371085/132940289-d2f6924a-c514-49c0-8ad4-dbf310959ad9.png)

**Comment by Merudo** [comment]
Ok I wrote down a compatibility patch for Ping Logger both with and without Raise My Hand enabled:

![image](https://user-images.githubusercontent.com/7371085/132940593-ce862864-c2f2-4cb5-b0bf-3b143ed8ee9d.png)
![image](https://user-images.githubusercontent.com/7371085/132940631-4179b8be-6ab4-4e4b-99f3-73f25a34df5e.png)

Ideally this would be fixed through changing the layout instead of hardcoding pixel size, but it works.

The patch:

```javascript
                    // Compatibility for Raise Hand module
					let playerWidthPixel = 22;
                    if (game.modules.has('raise-my-hand') && game.modules.get('raise-my-hand').active) {
                        playerWidthPixel += 20;
                        rootStyle.setProperty('--playerslh', '20px');
                    }

                    // Compatibility for Ping Logger module
                    if (game.modules.has('ping-logger') && game.modules.get('ping-logger').active) {
                        playerWidthPixel += 50;
                        rootStyle.setProperty('--playerslh', '20px');
                    }
				    
					if (playerWidthPixel > 22){
						rootStyle.setProperty('--playerwidth', `${playerWidthPixel}px`);
					}
```

**Comment by Merudo** [comment]
PR request #51 fixes the compatibility issue.

**Comment by saif-ellafi** [comment]
Released! Thanks a lot. Wouldn't have happened otherwise :)

**Comment by Merudo** [comment]
Unfortunately, with the new modifications the ping is still displayed on two lines when it reaches double digits:

![image](https://user-images.githubusercontent.com/7371085/132951545-9e9e05ff-47a4-4bf2-9ab2-237c52a7d7a0.png)

**Comment by saif-ellafi** [comment]
Hmm, I wonder why? It looks fine to me
![image](https://user-images.githubusercontent.com/27952699/132953296-145da84e-c25a-45cc-9dc8-9bff9352649a.png)

Which browser are you on?

**Comment by Merudo** [comment]
Low (0-9) pings work fine to me, but not when the ping is in the double digits (10+).

**Comment by saif-ellafi** [comment]
ahh got it, ok maybe I tightened the values to much. Will set them back to 50 as you proposed originally.

**Comment by saif-ellafi** [comment]
Another option would be to directly disable auto-hide mode when Ping Logger is enabled. I am not sure how high can the pings go and also a large box doesn't make sense

**Comment by saif-ellafi** [comment]
Ok, I will submit a solution, to hide the pings as well if Players is in auto-hide mode. This way the pings will be visible only on hover. Just like the rest of the titles.

**Comment by saif-ellafi** [comment]
Released with https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/tag/1.0.9

**Comment by Merudo** [comment]
I found what I think is a better solution, purely through CSS which also remove the need for the Raise my Hand patch.

In `#players#, I change `width: var(--playerwidth);` to `width: auto;`

then, I add these CSS styles:

```CSS
#players ol .player-active {
	display: inline-block;
	width: 8px;
	flex: auto;
}

.player.flexrow {
    display: block;
}
```

And this fixes it.

**Comment by Merudo** [comment]
Alternatively, we can keep `flex` and do the following

1. In #players, I change width: var(--playerwidth); to width: auto;
2. Add the following:

```
.player.flexrow {
    flex-wrap: nowrap;
}
```
3. To support the Raise my Hand module, we can add

```
#players ol .player-name {
    overflow: visible;
}
```
Otherwise the hand gets partially hidden.

**Comment by Merudo** [comment]
PR request opened to add back the ping.
