### ISSUE TITLE
0.8.9 breaks second column of left side bar.

### ISSUE THREAD

**Issue by foxreinhold** [saif-ellafi/foundryvtt-minimal-ui#44]
It  technically still works, it just doesn't truncate itself properly so it looks like the bar drags on forever.

![image](https://user-images.githubusercontent.com/77173822/129784806-2a33f63e-6df2-411f-9cb7-865944fc256e.png)

**Comment by saif-ellafi** [comment]
Thank you for reporting it so quickly! - My time is a bit limited but I just released support for 0.8.9 to the best of my abilities.

Enjoy!! Do let me know if anything looks strange, some things changed without notice on this release :)
