### ISSUE TITLE
"Right Side Panel Behaivor" set to Collapsed does not function with multiple Modules enabled.

### ISSUE THREAD

**Issue by Brimcon** [saif-ellafi/foundryvtt-minimal-ui#46]
This is a strange bug to report because its so inconsistent.
Using Find the culprit I could never find a single module that would be the cause this behavior.

Effectively with anything in the chat log. The right side panel would start open even with it set to collapsed.
I discovered that the more modules enabled, the higher the chance it would start open.
Even with one extra module enabled (In this example, Libwrapper) the chance increases.

To reproduce, enable more modules and refresh the page until it starts expanded.
This happens even with just Minimal UI and Lib - Color settings enabled.

Foundry 0.8.9, Minimal UI 1.0.5, Lib - Color settings 2.6.1

**Comment by saif-ellafi** [comment]
Thanks for reporting this. I am hoping to be able to figure out some sort of pattern to see what can be the reason. It did not happen on my side but haven't also investigated much. Any further info will be appreciated in the meantime.

**Comment by Brimcon** [comment]
During my testing, all I did was be in a world with the module with something in the chat log and then hit refresh. After a while the right side bar would be expanded, even with the setting "Start Collapsed" on.
I wish I could give more information than that.

**Comment by saif-ellafi** [comment]
Thanks, that actually helped. I found the bug. Will be fixing soon

**Comment by saif-ellafi** [comment]
Releasing in the next 5 minutes! Thanks
