### ISSUE TITLE
Left side bar does not save position

### ISSUE THREAD

**Issue by Wraithlord2015** [saif-ellafi/foundryvtt-minimal-ui#47]
Currently using foundry VTT 0.8.9 but able to duplicate issue with 0.8.8, and the issue occurs even with all other modules uninstalled &/or disabled.

I've found two issues that appear to be related - I'm unsure if it's specific to me, but adjusting the module settings for the "left controls position" - it will remain in place until I log out.

Upon logging back in, the left control bar isn't present - so I have to click on the foundry logo (at which point it re-appears) but it's no longer in the position that was chosen under the module settings.

As noted above, tried with all other modules uninstalled (as well as disabled), and the issue occurs with foundry VTT version 0.8.8 and 0.8.9; no error messages/notifications have been noted.

**Comment by saif-ellafi** [comment]
Thank you for taking the time to disable other mods and finding a relationship. Will take a look at this as soon as possible.

**Comment by saif-ellafi** [comment]
Hi @Wraithlord2015 I tried to reproduce this problem but I am unable to. I have a few questions:

1. You mention that when you log back in, the left control bar is not present. Why is this so? Nothing in this module should hide completely the left bar. Only FoundryVTT does that when you are don't have any Scene open.
2. Could you try resetting Minimal UI default settings to see if you happen to see any problems?
3. In all my tests, I tried different positions of the left side bar but even after log in and out I still see it where I left the settings.

Could you share some information on the browser you are using to use Foundry? and check again if you really have any mods enabled?
thanks

**Comment by Wraithlord2015** [comment]
Will post additional information in this post as soon as I have it. Just acknowledging that I saw your response. ;)

**Comment by saif-ellafi** [comment]
Thank you for exploring this! My recommendation is to use FoundryVTT Normally and track an issue if this happens again. 

ps: Windows  7 btw - come on haha :)  

If it happens again, feel free to open a new issue and share what were you doing when this happened. Maybe it was an update or a module that caused settings to reset to default. Otherwise the configuration should be saved on Foundry and there are no normal reasons to edit the settings.
