### ISSUE TITLE
Change Default

### ISSUE THREAD

**Issue by brunocalado** [saif-ellafi/foundryvtt-minimal-ui#48]
Hi.

Can you change the Default starting settings to always show everything?

People normally hide one or two elements only. It's annoying show everything everytime you start a new world.

Thank you.

**Comment by saif-ellafi** [comment]
Hi, so you mean when you install Minimal UI module, for the first time on every world, is to have settings that look exactly like Foundry Stock?

**Comment by brunocalado** [comment]
Yeah, but Minimal UI makes everything nicer. This is the great feature. Hide stuff is not so used because you need it all the time.

**Comment by saif-ellafi** [comment]
It is very difficult to tell how some stuff is used or not. Or did you make some polls? :) The idea of the defaults is to remind the users the things the module can do, also to give a clear impression that the UI changed to a usable state.

The two last games I played, the GM was using auto-hide left panels, but normally they just customize it.

It is only a problem if you create hundreds of worlds per day but hopefully it is not a big deal to change the defaults once in  a while.

What are your ideal defaults?

**Comment by saif-ellafi** [comment]
For when you are a GM, that is not a problem :)

For when you are a player, making that configuration as a player can help, like requested here: https://github.com/saif-ellafi/foundryvtt-minimal-ui/issues/31

**Comment by saif-ellafi** [comment]
After some thought, current defaults should be and are much more default friendly, and less of a first impression shock. Thank you @brunocalado
