### ISSUE TITLE
Allow Button Overflow

### ISSUE THREAD

**Issue by Avitale34** [saif-ellafi/foundryvtt-minimal-ui#49]
I have alot of modules lol and I love this one but it does not allow for button overflow. Is that an option that can be added?
![image](https://user-images.githubusercontent.com/65961637/132737066-97c6478c-55ec-4fbe-8444-e27ca08c0ef0.png)

**Comment by saif-ellafi** [comment]
True, it would be nice to have a scrolling wheel or something similar. Unfortunately I don't have the time now but will write it down on the backlog.

**Comment by saif-ellafi** [comment]
Should be fine in V9
