### ISSUE TITLE
[Bug] Scene Navigation Style : Start Collapsed doesn't work

### ISSUE THREAD

**Issue by Merudo** [saif-ellafi/foundryvtt-minimal-ui#50]
When `Scene Navigation Style` is set to `Start Collapsed`, it actually starts visible.

Not only that, it takes two clicks to make it collapsed. The first click does nothing.

**Comment by saif-ellafi** [comment]
Thank you, checking it out now

**Comment by saif-ellafi** [comment]
Should be fixed now @Merudo - Thank you for taking the time to report this. It has been broken since last release of Foundry 0.8.9

**Comment by Merudo** [comment]
Thank you, it works great now!
