### ISSUE TITLE
Problems with Ping Logger

### ISSUE THREAD

**Issue by P3rc3v4l1984** [saif-ellafi/foundryvtt-minimal-ui#54]
There are incompatibility problems with the PING LOGGER module, the response time is not shown in the user box.
I imagine that due to the information box size setting. Is it possible to fix this somehow?
Thank you

**Comment by saif-ellafi** [comment]
Hello @P3rc3v4l1984 -

The current support for the module is basic, but @Merudo has a proposal here: https://github.com/saif-ellafi/foundryvtt-minimal-ui/pull/53

I am unfortunately without a computer these days but will be releasing that improvement soon.

For the time being it will either show the ping on hover, or disable auto-hide option in the player list, to have it permanently visible. Make sure to be on the latest Minimal UI version as well.

Best Regards!

**Comment by Merudo** [comment]
> There are incompatibility problems with the PING LOGGER module, the response time is not shown in the user box.
> I imagine that due to the information box size setting. Is it possible to fix this somehow?
> Thank you

Currently, the ping should be shown during a mouse-over of the user box. Is that not working?

**Comment by P3rc3v4l1984** [comment]
The ping appears directly without doing anything, and nothing comes out, using other interface modules there is no problem.

**Comment by P3rc3v4l1984** [comment]
Ok, now its working, but you need use  auto-hide option!! Thank you for help!

**Comment by saif-ellafi** [comment]
So the pings are not visible in persistent mode?

**Comment by P3rc3v4l1984** [comment]
No, just in hide-mode

**Comment by Merudo** [comment]
My PR #53 also fixes this.

The problem is[ this part](https://github.com/saif-ellafi/foundryvtt-minimal-ui/blob/5d489dcc0a3654350a5d1f3da1898a2bb7256d7e/styles/component/players.css#L54), which hides the ping for all modes: 

```css
.pingLogger_pingSpan {
    display: None;
}
```

**Comment by saif-ellafi** [comment]
Thank you @Merudo - Now @P3rc3v4l1984 can enjoy Ping Logger with Minimal UI module in any player list format :)

**Comment by P3rc3v4l1984** [comment]
Clap clap, thank you! I appreciated!
