### ISSUE TITLE
 the left control bar overlaps the player bar.

### ISSUE THREAD

**Issue by cnutenor** [saif-ellafi/foundryvtt-minimal-ui#55]
Spectacular module! thanks.
the left control bar overlaps the player bar. is it possible to move them?
If I knew CSS I would try to move them using that module but I don't know. help.

**Comment by cnutenor** [comment]
![image](https://user-images.githubusercontent.com/51686939/139596807-afc94f32-ddb1-4eb0-8083-ed724528d9b6.png)

**Comment by saif-ellafi** [comment]
Hi @cnutenor - thank you for using Minimal UI module.

Unfortunately I cannot do much in this regard. It is a matter of the amount of modules you seem to have. The best thing to do is use a **small icons** left-sidebar configuration, put it to the highest position possible and if that does not suffice, hide or auto-hide the players box.

Regardless of Minimal UI or not, this is a Foundry issue unfortunately.
