### ISSUE TITLE
Minimal UI and Monk's Scene Navigation compatibility.

### ISSUE THREAD

**Issue by ironmonk88** [saif-ellafi/foundryvtt-minimal-ui#57]
I changed the expanded folder margin-top recently so that it drops down a little more when opened.
Could you change line 356 in the style sheet from `height: calc(var(--navilh) + 6px);` to 
```
height: calc(var(--navilh) + 2px);
margin-top: 4px;
```

Thank you.

**Comment by saif-ellafi** [comment]
Going in a release soon. Thanks.

**Comment by Gray-Geist** [comment]
> Going in a release soon. Thanks.

Did this ever release? Wanted to reply and say the issue still persists between the two. You can see in the image below that there should be many more folders under "Battlemaps" but it only shows one.

![image](https://user-images.githubusercontent.com/76698563/160179069-ddc7e5c1-db3c-467d-8f98-b93496e8beef.png)
