### ISSUE TITLE
[Ongoing] Support for Minimal UI with other modules

### ISSUE THREAD

**Issue by saif-ellafi** [saif-ellafi/foundryvtt-minimal-ui#6]
Please list any modules that need support:

- Unnoficial Card Support (Works)
- Quick Insert (Done)
- Search Anywhere (Done)
- Simple Dice Roller (Done)
- Combat Carousel (Works)
- Bullseye (Done)

**Comment by SalieriC** [comment]
- Calendar/Weather (not incompatible but maybe there is a way to hide it as well, maybe binding it to the left sidebar or something)
- Custom Hotbar (this is very important for me)

**Comment by Iankid** [comment]
Ernie's Modern UI

**Comment by saif-ellafi** [comment]
> Ernie's Modern UI

That will be a tough one :) Compatibility across UI modules can be quite painful. Going to give it a chance though. Thanks

**Comment by SalieriC** [comment]
- [ ] Monks Scene Navigation or Navigation Presets (whatever is easier to do) compatibility would be great. =)

**Comment by plutoneld** [comment]
The Monster Blocks module (https://foundryvtt.com/packages/monsterblock) doesn't work correctly with the minimize functionality. It doesn't minimize correctly (the title bar is twice as high sort of), and it doesn't restore properly.

**Comment by saif-ellafi** [comment]
Thanks @plutoneld glad that you found some interest in the minimize functionality! will check out that module

**Comment by saif-ellafi** [comment]
> The Monster Blocks module (https://foundryvtt.com/packages/monsterblock) doesn't work correctly with the minimize functionality. It doesn't minimize correctly (the title bar is twice as high sort of), and it doesn't restore properly.

This fix is fixed as part of the next release :D

**Comment by Mushie1** [comment]
Tidy UI game settings.
Not sure if the issue is in that module or this one.
With Tidy UI turned on, I could not have the left icons saved as "Always visible". when I saved changes, it still went into auto hide mode.  If I turned that module off, I could save the setting.

**Comment by saif-ellafi** [comment]
> Tidy UI game settings.
> Not sure if the issue is in that module or this one.
> With Tidy UI turned on, I could not have the left icons saved as "Always visible". when I saved changes, it still went into auto hide mode. If I turned that module off, I could save the setting.

Thanks @Mushie1 ! I really love that module, and it should work fine and actually encouraged.
I cannot however reproduce the issue you mention.

Here on my side it works fine:
![image](https://user-images.githubusercontent.com/27952699/116178041-2dd4ba80-a715-11eb-88b5-92755605ed33.png)

**Comment by Mushie1** [comment]
> Could you please discard any other issues and make sure you are on Minimal UI 0.8.8?

Just updated to 0.8.8 and I could not reproduce the bug.  So all good, thanks for the quick response!!
