### ISSUE TITLE
Default transparency change in latest update appears to ignore module settings

### ISSUE THREAD

**Issue by Farmeroz** [saif-ellafi/foundryvtt-minimal-ui#60]
The most recent update which changed the default transparency to 25 from 75 appears to now ignore the user or GM setting in the module regarding intial transparency.

I tried to set back to 75%, but it remains at 25% regardless of which of my wolrds I use or restarting the servers and so on.

**Comment by saif-ellafi** [comment]
Thank you @Farmeroz for letting me know so fast. Will fix it in a second, I made a small mistake.

**Comment by saif-ellafi** [comment]
Fixed in 1.1.4. One should not code at 5am. Thanks!

**Comment by Farmeroz** [comment]
Fantastic - thanks for the super fast fiix :-)
