### ISSUE TITLE
Module Integration Issues

### ISSUE THREAD

**Issue by ghost** [saif-ellafi/foundryvtt-minimal-ui#61]
Minimal UI plays rough with any modules that add a third column to the left bar menus (e.g. DF Curvy Walls, Monk's Wall Enhancements, and likely more). 
![image](https://user-images.githubusercontent.com/93453050/141736055-d1667b89-9d51-49f1-9060-ae0d9706a458.png)

There is also an issue with ripper's Taskbar and the macro menu with Minimal UI. Instead of popping upward on hover, it will move downward into the taskbar. This makes selecting the macro bar difficult and has its own separate thread [here](https://github.com/saif-ellafi/foundryvtt-minimal-ui/issues/52).

**Comment by saif-ellafi** [comment]
Thank you, it is unfortunately really time consuming to investigate other modules and understand how they work to make an appropriate adaptation. I will consider this but any developer's help will be appreciated on this direction. The amount of modules with conflict is also significantly increasing as Foundry increases in complexity.

**Comment by CardinalRed1** [comment]
Completely understandable. Definitely take your time with this as it is your code and your project. I crossposted it to DF's git and the issue has been brought up with ripper as well. [flamewave expressed interest in assisting](https://github.com/flamewave000/dragonflagon-fvtt/issues/211#issuecomment-968591737) and ripper is likely to help integrate his modules as well. Once again, thank you so much for your time and your module.

**Comment by saif-ellafi** [comment]
I would be curious if this is still valid in V9
