### ISSUE TITLE
BUG: Hotbar Default Position inaccurate

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#62]
For some reason when the hotbar is set to the Default position, it is way too far to the right. Changing the hotbar to another option, and then going back to Default will put it in the correct position, but the next time you refresh the window it breaks again and goes elsewhere.

**Comment by saif-ellafi** [comment]
Thank you for taking the time, will check it out immediately.

**Comment by saif-ellafi** [comment]
Fixed. Thank you for letting me know @GambetTV !!
