### ISSUE TITLE
Argon Combat UI Interaction

### ISSUE THREAD

**Issue by justinthejaguar** [saif-ellafi/foundryvtt-minimal-ui#64]
When I hit the cross-swords icon to bring up the Argon combat UI, the left panel opens. Nothing out of the ordinary in the console log when I do this. Version is 0.8.9

**Comment by Fridan99** [comment]
The same thing happens to me, when I open the Argon hud the left panel appears and locked (i have the autohide option).... only happens when i activate the hud (cross-swords), then when the hud is active it doesn't happen until you reactivate again..... it can be unlock normally pressin in the red lock.. but it's a curious bug. 🤣 🤣 🤣 🤣 🤣

**Comment by saif-ellafi** [comment]
Thanks, I might be able to patch this today (add a rule-out exception for this specific module). Ideally modules shouldn't "simulate" clicks, but well for now it is the fastest patch I can think of.

It this Argon Combat UI module a popular module overall?

**Comment by justinthejaguar** [comment]
> Is this Argon Combat UI module a popular module overall?

It only released on October 11, but imho it is one of the smoothest looking UI's I have seen for foundry. It is inspired by a D&D 5e game hud and UI. The game is called Solasta. I can see it becoming very popular in that it is extremely helpful in teaching players how to play D&D 5e. As to how many downloads it has, you would need to ask theripper93. As to why he is resistant to changing his use of .click(), I am not certain. I am not well-versed enough to understand what else that might tie into with his module.

**Comment by Fridan99** [comment]
> Thanks, I might be able to patch this today (add a rule-out exception for this specific module). Ideally modules shouldn't "simulate" clicks, but well for now it is the fastest patch I can think of.
> 
> It this Argon Combat UI module a popular module overall?

I believe that yes, it is a module that is becoming very popular and is under continuous maintenance.

**Comment by saif-ellafi** [comment]
hehe thanks all. Yes, asking for popularity is not at all of relevance in terms of support, just curiosity on whether it was something out there part of D&D people toolsets :D 
Glad to see that and will check it out myself

**Comment by saif-ellafi** [comment]
@justinthejaguar @Fridan99 could you give me a hand? - In general any button you press on the left-side controls will "lock" the sidebar. So clicking the swords button which also is a control button, will lock the left-side bar.

The lock was made out of convenience, in order to switch between controls and to prevent the sidebar from auto-hiding when the user is working on the tools. To hide it again, the unlock button is to be pressed.

**Comment by saif-ellafi** [comment]
Ahh I see just the ripper explained to me that is the token-hud what is triggering it.

**Comment by saif-ellafi** [comment]
Just released 1.1.9 -- Thank you @Fridan99 and @justinthejaguar for reporting this. Please confirm if all look good!

**Comment by Fridan99** [comment]
I can't automatically update minimal ui from 1.1.8 to 1.1.9

Foundry 0.8.9
![6](https://user-images.githubusercontent.com/86131373/146081968-c0ec1ec7-75ec-4157-b9a1-6adc10b3d787.jpg)

**Comment by saif-ellafi** [comment]
Ouch... This V9... Ok. I have deleted the Foundry V9 release. Please wait about 5 minutes and let me know if works then! Thank you

**Comment by justinthejaguar** [comment]
This works perfectly on V0.8.9 for me. Thank you!

**Comment by Fridan99** [comment]
> This works perfectly on V0.8.9 for me. Thank you!

How did you update? manually? in the repository app I can't do it

**Comment by justinthejaguar** [comment]
I run mine using node.is on a raspberry pi. I just updated it in the module screen.

**Comment by Fridan99** [comment]
Minimal ui 1.1.9
https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/download/1.1.9/module.json 

Upgrade to this link, if anyone use 0.8.9 Foundry.... courtesy of the module author. Apparently it is not possible to update correctly from the app repository. Just paste in the Manifest URL and install.

**Comment by saif-ellafi** [comment]
Fixed
