### ISSUE TITLE
Suggestion: left bar control position

### ISSUE THREAD

**Issue by Fridan99** [saif-ellafi/foundryvtt-minimal-ui#65]
I don't know if it is possible, but it would be useful to have the position control of the left bar. When you have too many things in the bar, it tends to hide down.... if you could raise it slightly with some option, it would be useful. 
![6](https://user-images.githubusercontent.com/86131373/146084059-45c258e8-4203-4fdd-b74c-312bf9503943.jpg)

It's just an idea, in case you see it useful and it could be done. 

In the case of the img, if it could be raised, I would probably roll the cam, and adjust the bar a little higher. That's the bad thing about having so many options on the left bar 😂😂😂. Without the minimal ui it would be IMPOSSIBLE.

**Comment by saif-ellafi** [comment]
That is unfortunately something Foundry has to help us with!!! For now let's wait until V9 and see how things evolve. The left side panel changes significantly in V9 and many features may no longer be supported

**Comment by saif-ellafi** [comment]
I believe this has been improved by Foundry's V9!
