### ISSUE TITLE
Compatibility for ripper's taskbar

### ISSUE THREAD

**Issue by CasanovaSekova** [saif-ellafi/foundryvtt-minimal-ui#66]
Theoretically the code below should work if inserted in the minimalui.js file
https://github.com/CasanovaSekova/foundryvtt-minimal-ui/pull/1

```
if (game.modules.get('foundry-taskbar')  && game.modules.get('foundry-taskbar').active) {
  rootStyle.setProperty('--playerbot', '60px');
  rootStyle.setProperty('--hotbarypos', '60px');
  rootStyle.setProperty('--hotbarhv', '70px');
}
```

I made the same types of changes in the .css file for minimal ui to get around the taskbar and macro bar + player bar overlapping in minimal ui.

Also sorry for the bizarre format of this :( Still getting used to github

EDIT: The code no longer works for later vers of minimal ui. Likely because of restructuring. The concept for a solution is still the same though (check if Taskbar is active, ideally check if move macros and playerlist in Taskbar is active, move them up 60px if true).

**Comment by saif-ellafi** [comment]
Thanks! Compatibility is the challenge. For now my preferred strategy is to wait for Foundry V9 before making changes to the current branch. We'll have to see how things evolve from there as V9 changes many things!

**Comment by ravingdragoon** [comment]
I would like to second this request. I am having issues with the macro bar dropping below the taskbar when I try to change the page on the macro bar, even though I have the macro bar set to be always visible.

**Comment by saif-ellafi** [comment]
Sorry @CasanovaSekova @ravingdragoon, this proposed module's compatibility is behind a paycheck. Totally out of my desired reach. Do check out my module **Window Controls** it has a Taskbar mode. Probably not as fancy as one professionally made but still... :)
