### ISSUE TITLE
BUG: FPS Counter is moved with no option to change its position

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#67]
By default Foundry places the FPS meter on the bottom right of the screen. Your module puts it in the bottom left, which is obscured by the player list, and from what I can tell there's no option to move it elsewhere. It'd be cool if there was an option to manually adjust the position of the FPS meter.

**Comment by saif-ellafi** [comment]
Thanks will fix this in 1.3.1

**Comment by saif-ellafi** [comment]
Fixed! Please let me know otherwise
