### ISSUE TITLE
Minimal UI Printing True/False when minimizing/maximizing the Chat Window

### ISSUE THREAD

**Issue by Brimcon** [saif-ellafi/foundryvtt-minimal-ui#69]
As said in the title, whenever you minimize or maximize the chat window
![image](https://user-images.githubusercontent.com/7198283/146976938-45e0b218-9068-4cdb-8645-589dff2557e1.png)
is printed in the console.

**Comment by saif-ellafi** [comment]
Ooops :D

**Comment by saif-ellafi** [comment]
Fixed! Thank you
