### ISSUE TITLE
Colourable outer glow

### ISSUE THREAD

**Issue by SalieriC** [saif-ellafi/foundryvtt-minimal-ui#7]
Currently it can only be the Foundry default orange-red-ish. I'd like to configure the outer glow of side- and macro-bar and preferably the one in the right sidebar as well:
![image](https://user-images.githubusercontent.com/1230041/112123043-30496f00-8bc1-11eb-914b-6bfa2b304637.png)

**Comment by saif-ellafi** [comment]
Thanks! good idea :)

**Comment by saif-ellafi** [comment]
done! Please take a look :)
