### ISSUE TITLE
Transparency settings for Left Sidebar only take effect on click

### ISSUE THREAD

**Issue by Brimcon** [saif-ellafi/foundryvtt-minimal-ui#70]
When loading a world or refreshing the page the left sidebar does not obey transparency settings until clicked upon.
Eg: I have transparency set to 5% and the left sidebar is at default value. Can be seen here with the difference between the navigation controls vs left sidebar.
![image](https://user-images.githubusercontent.com/7198283/146977990-ef009902-cfa0-4a22-8a42-5ec432a8c924.png)

**Comment by saif-ellafi** [comment]
Thank you for reporting this! Will address soon

**Comment by saif-ellafi** [comment]
Fixed and released in 1.3.2 thank you very much! Let me know for anything else!
