### ISSUE TITLE
Navigation Overflow

### ISSUE THREAD

**Issue by smturg** [saif-ellafi/foundryvtt-minimal-ui#75]
After update to Foundry 9.241 - overflow of the Nav bar doesn't seem to be reading correctly. It runs to beyond the end of the row, through the right side panel (whether collapsed or not), and past the end of the window. 

The last item in the row will run past the edge of the screen, and if another item is added to the toggle, it will overflow from there. Likewise, it doesn't resize based on whether the right side panel is collapsed or not.

I tested this with all other modules off just to be sure.

Thanks in advance for looking into this! :)

![Minimal UI Overflow](https://user-images.githubusercontent.com/97303899/148575300-1644c86a-d8b4-4920-b26c-f20de9594057.jpg)

**Comment by saif-ellafi** [comment]
Hey @smturg - Thanks! Will check this out!!

**Comment by saif-ellafi** [comment]
@smturg - kindle check 1.4.7 when possible, as this should be now fixed! Thank you

**Comment by smturg** [comment]
@saif-ellafi - Cheers! Can confirm 1.4.7 addressed the overflow issue. Greatly appreciated!
