### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [saif-ellafi/foundryvtt-minimal-ui#77]
Hi.

Please remove the foundry vtt warning. 
![image](https://user-images.githubusercontent.com/4999783/148644257-5bdf145d-8b0d-4f99-b989-b94a87192a83.png)

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9"

**Comment by saif-ellafi** [comment]
Hi. I am not sure, this was made by choice. I cannot guarantee that if Foundry updates, Minimal UI will continue to work correctly. Any style change that Foundry makes in any V9 release could have a compatibility risk.

**Comment by brunocalado** [comment]
> Hi. I am not sure, this was made by choice. I cannot guarantee that if Foundry updates, Minimal UI will continue to work correctly. Any style change that Foundry makes in any V9 release could have a compatibility risk.

Yes, I understand. But, the foundry add this because their plans is not make breaking changes in a major version (v9, v10, etc).

With their build system a module without something like **"compatibleCoreVersion":"9"** will always have the warning tag. 

I don't think there is no risk in a very small bug, but I don't think it you break minimal ui.

docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by saif-ellafi** [comment]
Done a few releases ago!
