### ISSUE TITLE
Lock/Unlock Macro Bar when auto-hidden (default) mode

### ISSUE THREAD

**Issue by jbblily** [saif-ellafi/foundryvtt-minimal-ui#8]
I cannot add new macro from macro directory when it's auto-hidden (default) mode.
It automatically collapses while opening macro directory.
Like left sidebar, I want 'lock/unlock' option.

**Comment by saif-ellafi** [comment]
Thank you for reporting this! I will look into it immediately.

**Comment by saif-ellafi** [comment]
Done in [0.3.x](https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/tag/0.3.4)
Thanks!
