### ISSUE TITLE
Compatibility issue with combat carousel control button

### ISSUE THREAD

**Issue by yjeroen** [saif-ellafi/foundryvtt-minimal-ui#80]
![image](https://user-images.githubusercontent.com/1303988/149401589-d5863091-e394-486e-a132-382361ef6237.png)

The combat carousel icon (on the bottom) isn't made smaller.

```html
<li class="scene-control " data-control="effects" data-canvas-layer="specials" title="Effect Controls">
            <i class="fas fa-magic"></i>
        </li>

<li class="scene-control" data-control="combat-carousel" title="Combat Carousel - click to toggle visibility, right-click to reset position">
    <img src="modules/combat-carousel/icons/empty-carousel-solid.svg" class="carousel-icon">
    <div class="wrapper">
        <i class="fas fa-caret-down collapse-indicator"></i>
    </div>
</li>

```

**Comment by saif-ellafi** [comment]
Hi @yjeroen thanks for reporting this

Not my intention to sound blunt, but Minimal UI does not make any particular distinction between control buttons. Adding a particular exception for Combat Carousel would be unfair from my side. This should be reported over to Combat Caroussel, so the module owner uses standard Windows properties, like the rest of the buttons.

**Comment by yjeroen** [comment]
Understand your point!
I've also opened an issue on their end:
https://github.com/death-save/combat-carousel/issues/125

**Comment by saif-ellafi** [comment]
Thank you, I hope this can be resolved on the other side of the story! It is indeed a nice module. Ping me again if you get resistance on the other side, I can consider some hacky wacky stuff, but hopefully not!
