### ISSUE TITLE
Compatibility issues with Custom Hotbar

### ISSUE THREAD

**Issue by adotor** [saif-ellafi/foundryvtt-minimal-ui#81]
Using MinimalUI with Custom Hotbar CHB is incompatible since I upgraded to Foundry v9

Foundry: 9 Build 242
MinimalUI: 1.4.11
CHB: 2.2.0

See Screenshot.

![image](https://user-images.githubusercontent.com/7715059/149529454-12e40ee4-0c10-455c-abe5-cf64648f888c.png)

**Comment by saif-ellafi** [comment]
Hey @adotor - it works pretty fine for me on first impression.
In any case, I don't plan on improving compatibility with Custom Hotbar any further.
The module has made 0 effort on being compatible with other modules, and it uses style elements with tag `important`, placing itself above any other modules. I am not a big fan of such approaches. But yet, there are code in Minimal UI that makes it work with it, overall.
![image](https://user-images.githubusercontent.com/27952699/150336843-cf3dbcc4-e9a2-435e-9a20-04541a6ede58.png)

**Comment by adotor** [comment]
Thank you fpr your efforts. 

I wasn‘t aware of the state of the CHB Module regarding UI compatibility. I fully agree: A module implemented for a framework should behave as minmal invasive as possible.

**Comment by saif-ellafi** [comment]
Thank you for understanding
