### ISSUE TITLE
Left Sidebar Formatting Issue - v9

### ISSUE THREAD

**Issue by cr45hmurphy** [saif-ellafi/foundryvtt-minimal-ui#83]
After upgrading to FVTT v9, left sidebar appears to be messed up when Minimal UI is enabled. Hotbar and right sidebar appear to behave as expected.

![image](https://user-images.githubusercontent.com/4840152/149672246-4643caa5-ced6-4bbd-a949-99f6f2d7dede.png)

**Comment by saif-ellafi** [comment]
Oh wow. That is a whole new level of broken. @cr45hmurphy can you please Press F12 and send me a screenshot of any errors (RED colored text)?
I believe you have something going on. Also please try uninstall and reinstall minimal-ui, making sure you are on the last version too!

**Comment by cr45hmurphy** [comment]
@saif-ellafi Can do! But, before I do that, I do NOT think the issue is actually Minimal UI, and I may have pulled the trigger to quickly. Even with it off, the left sidebar is not working, so that tells me it is a different module causing issues. I will update shortly.

**Comment by cr45hmurphy** [comment]
Update:

Left sidebar appears to be functional, with and without Minimal UI. However, with Minimal UI enabled, I cannot actually hide it. Here is a screenshot of the console:

![image](https://user-images.githubusercontent.com/4840152/149672982-19fa6b29-5489-496c-98fb-6d8a864cebbd.png)

**Comment by saif-ellafi** [comment]
I suggest following this on the Foundry VTT Discord! These errors don't seem to be related at all with Minimal UI. Something else is going on here. Errors seem to relate to initiative, better rolltables and turn makers. Make sure your modules are compatible with V9 too.

**Comment by cr45hmurphy** [comment]
@saif-ellafi Understood. I'm going to close this out. My apologies for jumping the gun!
