### ISSUE TITLE
Give option to disable Glow and Bounce

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#9]
Great module! But I do find it a bit distracting that the left bar and the macro bar are both permanently glowing, even if I have them set to "always display". Also the macro bar bounces when you hover over it, even if it's set to always display. Similarly, there's a bit of jitter to the entire left bar as you mouseover various icons that I find pretty distracting. Thanks!

**Comment by saif-ellafi** [comment]
Improved significantly in release https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/tag/0.3.4
Please take a look :)

**Comment by GambetTV** [comment]
The Bounce is gone! And the transparent colors works good. Thanks!
