### ISSUE TITLE
Cameras overlap the hotbar

### ISSUE THREAD

**Issue by dhorkin** [saif-ellafi/foundryvtt-minimal-ui#92]
This should mostly speak for itself. Using the latest Foundry v9 version. This only happens with Minimal UI turned on.

![image](https://user-images.githubusercontent.com/16787581/162681926-051b74e3-ce50-4dc9-8679-fe0c967e38ea.png)

**Comment by saif-ellafi** [comment]
Fixed. Thanks @dhorkin
I hope Foundry stops changing style names between minor updates.
