### ISSUE TITLE
Some buttons break when camera undocked and disabled

### ISSUE THREAD

**Issue by Killasaurus-Warbear** [saif-ellafi/foundryvtt-minimal-ui#93]
When "No Camera Behavior" is set to "Default" or "Reduced" and the camera is Popped Out/Undocked the buttons for "Send to Dock" and "Configure Settings" move and become impossible to click until camera is re-enabled. 

Also, when camera is Docked and Disabled and "No Camera Behavior" is set to "Default", the same two buttons from above move into an more inconvenient location (over the nameplate of the avatar) than where they move when the "No Camera Behavior" setting is set to "Reduced". 

Attached pictures to show issues with specific configurations. 

Minimal UI is the only active module while taking these images.

![Camera Issues Minimal UI](https://user-images.githubusercontent.com/50350483/163632021-c2373464-003d-439f-8b9c-8902ae0903e1.png)

**Comment by saif-ellafi** [comment]
Thanks for reporting it @Killasaurus-Warbear -
At this point, my best bet is to disable this feature... Foundry VTT keeps changing the way it works every release, and it is more pain than it's worth it to keep fixing it everytime :)

**Comment by Killasaurus-Warbear** [comment]
That's too bad. The feature is awesome, and my players with smaller monitors/laptops definitely appreciate it. But, I definitely understand disabling it at least until Foundry stops tweaking it so frequently. It still amazes me that this isn't a standard feature of Foundry considering how much screen real estate those boxes take up by default.

**Comment by saif-ellafi** [comment]
Hi @Killasaurus-Warbear - I hope I got it right this time. Fixed in .24 - Could you please check? Thanks

**Comment by Killasaurus-Warbear** [comment]
It looks like all the buttons are back where they belong. I'm not sure if this is the intent or not, but the avatars don't become "Reduced" down to nameplates when Popped-Out/Undocked, but everything else appears to be functioning as expected. Thanks!

**Comment by saif-ellafi** [comment]
> It looks like all the buttons are back where they belong. I'm not sure if this is the intent or not, but the avatars don't become "Reduced" down to nameplates when Popped-Out/Undocked, but everything else appears to be functioning as expected. Thanks!

It is intended, that popout mode does not get reduced. I am mostly sure it was like this in the previous Foundry VTT version.
Floating windows with reduced mode would be weird, by just showing the name bar.
You're welcome
